version: "3.8"

services:

  accounts:
    image: visbank/accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - visbank-network
    
  loans:
    image: visbank/loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - visbank-network
    
  cards:
    image: visbank/cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - visbank-network
    
networks:
  visbank-network: